version: '3.7'
services:
  samba:
    build: .
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139" 
      - "445:445"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    image: samba
    container_name: samba
